// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SimpleStorage$Type } from "./SimpleStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleStorage"]: SimpleStorage$Type;
    ["contracts/SimpleStorage.sol:SimpleStorage"]: SimpleStorage$Type;
  }
}
